# Generated by Django 5.1.1 on 2024-12-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Producto',
        ),
    ]
